Repository wiremock/wiremock-state-extension, pull requests merged in 2023-10, with the labels that each got.

#66 refactor: extend logging for happy cases
  src/main/java/org/wiremock/extensions/state/extensions/DeleteStateEventListener.java
  src/main/java/org/wiremock/extensions/state/extensions/RecordStateEventListener.java
  src/main/java/org/wiremock/extensions/state/extensions/StateHandlerbarHelper.java
  src/main/java/org/wiremock/extensions/state/extensions/StateRequestMatcher.java
  src/main/java/org/wiremock/extensions/state/internal/ContextManager.java
  src/main/java/org/wiremock/extensions/state/internal/ExtensionLogger.java
Labels: enhancement, hacktoberfest

#72 Maven central release
  .github/workflows/release.yml
  build.gradle
Labels: chore

#74 Escape @ in Javadoc to fix Java 11 builds
  src/main/java/org/wiremock/extensions/state/StateExtension.java
Labels: chore

#75 Document the module release process
  DEVELOPMENT.md
Labels: documentation

#76 Fix release pipeline to trigger on `publish`
  .github/workflows/release.yml
Labels: chore

#77 Fix environment variables propagation in signing and release publishing
  build.gradle
Labels: chore

#78 Release flow: Fix signing key propagation
  .github/workflows/release.yml
Labels: chore

#79 Code signing: Do not use publishing as extension
  build.gradle
Labels: chore

#80 Fix Sonatype credentials propagation
  build.gradle
Labels: chore

#82 Use the default nexus URL for the legacy Maven Central server
  build.gradle
Labels: chore

#84 Add quick access badges to the root
  README.md
Labels: documentation

#85 Fix CI builds
  .github/workflows/build-and-test.yml
  .gitignore
  build.gradle
Labels: chore

#86 Update build.gradle
  build.gradle
Labels: chore

#87 Update build.gradle
  build.gradle
Labels: chore

#88 Update build.gradle
  build.gradle
Labels: chore
